version: "3"
services:
  proxy:
    image: abiosoft/caddy:no-stats
    restart: on-failure
    ports:
      - 80:80
      - 433:433
    environment:
      - ACME_AGREE=true
    volumes:
      - ./proxy/Caddyfile:/etc/Caddyfile
      # Caddy will save SSL certs here
      - $HOME/.caddy:/root/.caddy
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "2"

  search-index-builder:
    build: "./search-index-builder"
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "2"

  names-search-service:
    build: "./names-search-service"
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "2"

  redis:
    image: "redis:alpine"
    volumes:
    - redis-data:/data
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "2"

volumes:
  redis-data:
