version: "3"
services:
  proxy:
    image: umputun/nginx-le:latest
    hostname: proxy
    container_name: proxy
    restart: always
    depends_on:
      - "names-search-service"

    volumes:
      - ./proxy/ssl:/etc/nginx/ssl
      - ./proxy/service.conf:/etc/nginx/service.conf
    ports:
      - "80:80"
      - "443:443"

    environment:
      - TZ=Europe/Amsterdam
      - LETSENCRYPT=true
      - LE_EMAIL=vladimir.guguiev+import-plugin@gmail.com
      - LE_FQDN=search.importcdn.com
      #- SSL_CERT=le-crt.pem
      #- SSL_KEY=le-key.pem
      #- SSL_CHAIN_CERT=le-chain-crt.pem

  names-search-service:
    build: "./names-search-service"
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "2"
    environment:
      - TZ=Europe/Amsterdam

  search-index-builder:
    build: "./search-index-builder"
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "2"
    environment:
      - TZ=Europe/Amsterdam

  redis:
    image: "redis:alpine"
    volumes:
    - redis-data:/data
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "2"
    environment:
      - TZ=Europe/Amsterdam

volumes:
  redis-data:
